Add spring-cloud-azure-native-configuration build customizer
Azure/azure-spring-initializr pull request #39
Opened 2022-04-25 02:51 UTC by moarychan

The artifact id `spring-cloud-azure-native-configuration` will be added automatically when there's any Spring Cloud Azure coordinate that supports Spring Native.

2022-04-25 04:03 UTC, backwind1233 commented on start-site/src/main/resources/application.yml
> +          id: azure-native-configuration
add bom section here

2022-04-25 04:05 UTC, backwind1233 commented on initializr-extension/src/main/java/com/azure/spring/initializr/extension/dependency/springazure/AbstractSpringCloudAzureNativeBuildCustomizer.java
> +        Dependency.Builder<?> builder = withCoordinates("com.azure.spring", "spring-cloud-azure-native-configuration");
can we just use 
```
build.dependencies()
             .add("azure-native-configuration") 
```
?

2022-04-25 04:34 UTC, moarychan commented on initializr-extension/src/main/java/com/azure/spring/initializr/extension/dependency/springazure/AbstractSpringCloudAzureNativeBuildCustomizer.java
> +        Dependency.Builder<?> builder = withCoordinates("com.azure.spring", "spring-cloud-azure-native-configuration");
OK

2022-04-25 04:36 UTC, moarychan commented on start-site/src/main/resources/application.yml
> +          id: azure-native-configuration
It's a special case that is not managed in spring-cloud-azure-dependencies bom.

2022-04-25 06:16 UTC, backwind1233 commented on start-site/src/main/resources/application.yml
> +          id: azure-native-configuration
Ok, I see

2022-05-18 02:23 UTC, saragluna requested changes

2022-05-18 02:23 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/autoconfigure/ExtendDependencyProjectGenerationConfiguration.java
> +    @ConditionalOnRequestedDependency("cloud-starter-sleuth")
These show an inconsistent indentation.

2022-05-18 02:23 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/extension/dependency/springazure/AbstractSpringCloudAzureNativeBuildCustomizer.java
> +    private static final Log logger = LogFactory.getLog(AbstractSpringCloudAzureNativeBuildCustomizer.class);
Seems like in this PR we are using `apache.commons.logging`, but in another PR we are using SLF4J.

2022-05-19 08:20 UTC, moarychan commented on initializr-extension/src/main/java/com/azure/spring/initializr/extension/dependency/springazure/AbstractSpringCloudAzureNativeBuildCustomizer.java
> +    private static final Log logger = LogFactory.getLog(AbstractSpringCloudAzureNativeBuildCustomizer.class);
https://docs.spring.io/spring-framework/docs/5.0.0.M5/spring-framework-reference/html/overview.html#overview-not-using-commons-logging, the log should be unified use of slf4j API.

2022-12-05 03:42 UTC, stliu commented
drop from plan

2022-12-05 03:42 UTC, closed without merging