[POC] Add project generation request statistics support
Azure/azure-spring-initializr pull request #63
Opened 2022-05-16 10:57 UTC by moarychan

Add log for project request usage, we use the Event hubs to transform the request event and finally save the data into 2 tables in Azure Data Explorer, this feature is disabled by default.
Use two log structures to record and send the event to different Event Hub:
- Project generation success
- Project generation failed

2022-05-17 02:34 UTC, stliu commented on start-site/src/main/resources/application.yml
> +        connection-string: ${EVENT_HUBS_INITIALIZR_CONNECTION_STRING}
we should use MSI and make this application **credential-free**

2022-05-18 01:03 UTC, backwind1233 commented on start-site/pom.xml
> +    <dependency>
wrong indent

2022-05-18 01:19 UTC, backwind1233 commented on start-site/src/main/resources/application.yml
> +  cloud:
can we move this into `initializr-extention` module?

2022-05-18 02:16 UTC, saragluna requested changes

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/autoconfigure/ExtendInitializrAutoConfiguration.java
> +    private static final Logger LOGGER = org.slf4j.LoggerFactory.getLogger(ExtendInitializrAutoConfiguration.class);
Why do we have the package name here for LoggerFactory?

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/autoconfigure/ExtendInitializrProperties.java
> +    @JsonIgnore
Same here for the `LoggerFactory`

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/autoconfigure/ExtendInitializrAutoConfiguration.java
> +    @ConditionalOnProperty(value = "extend.initializr.stats.eventhub.enabled", havingValue = "true")
eventhubs

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/autoconfigure/ExtendInitializrAutoConfiguration.java
> +    public StatProjectGenerationLogProcessor eventHubProcessor(ExtendInitializrProperties properties,
Please change the bean name to match its usage

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/autoconfigure/ExtendInitializrProperties.java
>  //    @NestedConfigurationProperty
Please help remove this commented out line

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/autoconfigure/StatsProperties.java
> +	@NestedConfigurationProperty
No need for `@NestedConfigurationProperty`; when a class is a static internal class, the `@NestedConfigurationProperty` can be omitted

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/autoconfigure/StatsProperties.java
> +	public static final class Eventhub {
The indentation doesn't seem correct.

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/autoconfigure/StatsProperties.java
> +	public static final class Eventhub {
Should we call it `Eventhubs`?

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/web/project/EventHubStatProjectGenerationLogProcessor.java
> +public class EventHubStatProjectGenerationLogProcessor implements StatProjectGenerationLogProcessor {
EventHubs

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/web/project/GenerationEventLogConverter.java
> +public class GenerationEventLogConverter implements Converter<ProjectRequestEvent, GenerationEventLog> {
should this be a final class if with a private ctor?

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/web/project/ProjectFailedEventLogConverter.java
> +public class ProjectFailedEventLogConverter implements Converter<ProjectFailedEvent, GenerationFailedEventLog> {
Should this class be called `GenerationFailedEventLogConverter`

2022-05-18 02:16 UTC, saragluna commented on initializr-extension/src/main/java/com/azure/spring/initializr/web/project/StatProjectGenerationLogProcessor.java
> +public interface StatProjectGenerationLogProcessor {
How about changing the name to `ProjectGenerationStatisticsProcessor`?

2022-05-19 02:25 UTC, stliu commented on initializr-extension/src/main/java/com/azure/spring/initializr/web/project/EventHubsProjectGenerationStatisticsProcessor.java
> +    public void sendRequest(String json) {
don't like this method naming, it couples with impl

2022-05-19 05:57 UTC, moarychan commented on initializr-extension/src/main/java/com/azure/spring/initializr/web/project/ProjectGenerationStatisticsProcessor.java
> +    void sendRequest(String json);
Indeed, I will refactor the design here.

2023-01-05 06:52 UTC, moarychan commented
Closing it due to dropping from the plan.

2023-01-05 06:52 UTC, closed without merging